### ISSUE TITLE
Complete Advanced React and Redux Course

### ISSUE THREAD

**Issue by Jpere547** [Jpere547/PersonalCoursesAndProjects#46]
### Advanced React and Redux 
Walkthroughs on advanced React and Redux - Authentication, Testing, Middlewares, HOC's, and Deployment 

- Build a scaleable API with authentication using Express, Mongo, and Passport
- Learn the differences between cookie-based and token-based authentication
- Figure out what a Higher Order Component and how to use it to write dramatically less code
- Write Redux middleware from scratch to uncover what is happening behind the scenes with Redux
- Set up your own testing environment with Jest and Enzyme
- Realize the power of building composable components

## Sections:
- [ ] Welcome
- [ ] Testing
- [ ] Higher Order Components (HOC)
- [ ] Middlewares with Redux
- [ ] Server Setup - Authentication
- [ ] Client Side Authentication
- [ ] Testing With React
- [ ] Test Environment Setup with React
- [ ] Higher Order Components with React
- [ ] Middleware with React
- [ ] Client Side Authentication with React
- [ ] Extras
