### ISSUE TITLE
Complete Build A Chat App with React, Redux, and Firebase Course

### ISSUE THREAD

**Issue by Jpere547** [Jpere547/PersonalCoursesAndProjects#48]
### Build a Chat App with React, Redux, and Firebase 

Create a complete, full-stack chat application from front to back with React, Redux, Firebase 5, and Semantic UI React

- Create full-stack apps with React, Redux and Firebase, among other tools in the React ecosystem
- Make complete React apps from scratch, from setting up their dev environment to deployment on the web
- Integrate Redux and Firebase with React apps using straightforward, practical patterns
- Learn every major part of Firebase: the real-time database, storage, rules, listeners and deployment with Firebase tools

## Sections
- [ ] Project Setup
- [ ] User Authentication with Firebase
- [ ] Form Validation and Authentication Error Handling
- [ ] Integrate Redux for Global State
- [ ] Building Out Chat Console
- [ ] Adding / Displaying Public Channels
- [ ] Adding / Displaying Messages on Public Channels
- [ ] Adding / Uploading Messages with Media Files
- [ ] Sending Direct Messages to Users
- [ ] Notifications for New Messages on Public Channels
- [ ] Starred Component to Favorite / Unfavorite Channels
- [ ] Color Picker to Change App Colors
- [ ] Change and Edit User Avatar
- [ ] Display Animations when Users Typing
- [ ] Adding Emoji Picker, Loading Skeleton, Automatic Scroll to Bottom, Key Shortcuts
- [ ] Removing Listeners, Securing our App with Firebase Rules
- [ ] Deploying our App with Firebase Tools
