### ISSUE TITLE
Complete Angular & NodeJS - The MEAN Stack Guide

### ISSUE THREAD

**Issue by Jpere547** [Jpere547/PersonalCoursesAndProjects#51]
## Angular & NodeJS - The MEAN Stack Guide

Learn how to connect your Angular Frontend to a NodeJS & Express & MongoDB Backend by building a real Application.

- Build real Angular + NodeJS applications
- Understand how Angular works and how it interacts with Backends
- Connect any Angular Frontend with a NodeJS Backend
- Use MongoDB with Mongoose to interact with Data on the Backend
- Use ExpressJS as a NodeJS Framework
- Provide a great user experience by using Optimistic Updating on the Frontend

### Sections
- [x] Getting Started
- [x] Understanding the Basics
- [x] Adding NodeJS
- [x] Adding MongoDB
- [x] Enhancing the App
- [x] Adding Image Upload
- [x] Adding Pagination
- [x] Adding User Authentication
- [x] Authorization
- [x] Handling Errors
- [x] Optimizations
- [x] Deploying the App
- [x] Wrapup
